# Generated by Django 2.1.3 on 2019-09-11 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeDesejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.Cliente', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'ListaDeDesejo',
                'verbose_name_plural': 'ListaDeDesejos',
            },
        ),
    ]
