# Generated by Django 2.1.3 on 2019-09-11 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_listadedesejos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listadedesejos',
            old_name='id_produto',
            new_name='produto',
        ),
        migrations.AlterField(
            model_name='listadedesejos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listaDeDesejos', to='cliente.Cliente', verbose_name='Sala'),
        ),
    ]
