# Generated by Django 2.1.3 on 2019-09-11 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20190911_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadedesejos',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='ListaDeDesejos',
        ),
    ]
