# Generated by Django 2.1.3 on 2019-09-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_auto_20190911_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeDesejos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_de_desejos', to='cliente.Cliente', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'ListaDeDesejo',
                'verbose_name_plural': 'ListaDeDesejos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='listadedesejos',
            unique_together={('produto', 'cliente')},
        ),
    ]
