# Generated by Django 2.1.3 on 2019-09-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaDeDesejos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadedesejos',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lista_de_desejos', to='cliente.Cliente', verbose_name='Cliente'),
        ),
    ]
